// Generated Code - DO NOT EDIT !!
// generated by 'emugen'


#include <string.h>
#include "renderControl_wrapper_context.h"


#include <stdio.h>

int renderControl_wrapper_context_t::initDispatchByName(void *(*getProc)(const char *, void *userData), void *userData)
{
	void *ptr;

	ptr = getProc("rcGetRendererVersion", userData); if(ptr) set_rcGetRendererVersion((rcGetRendererVersion_wrapper_proc_t)ptr);
	ptr = getProc("rcGetEGLVersion", userData); if(ptr) set_rcGetEGLVersion((rcGetEGLVersion_wrapper_proc_t)ptr);
	ptr = getProc("rcQueryEGLString", userData); if(ptr) set_rcQueryEGLString((rcQueryEGLString_wrapper_proc_t)ptr);
	ptr = getProc("rcGetGLString", userData); if(ptr) set_rcGetGLString((rcGetGLString_wrapper_proc_t)ptr);
	ptr = getProc("rcGetNumConfigs", userData); if(ptr) set_rcGetNumConfigs((rcGetNumConfigs_wrapper_proc_t)ptr);
	ptr = getProc("rcGetConfigs", userData); if(ptr) set_rcGetConfigs((rcGetConfigs_wrapper_proc_t)ptr);
	ptr = getProc("rcChooseConfig", userData); if(ptr) set_rcChooseConfig((rcChooseConfig_wrapper_proc_t)ptr);
	ptr = getProc("rcGetFBParam", userData); if(ptr) set_rcGetFBParam((rcGetFBParam_wrapper_proc_t)ptr);
	ptr = getProc("rcCreateContext", userData); if(ptr) set_rcCreateContext((rcCreateContext_wrapper_proc_t)ptr);
	ptr = getProc("rcDestroyContext", userData); if(ptr) set_rcDestroyContext((rcDestroyContext_wrapper_proc_t)ptr);
	ptr = getProc("rcCreateWindowSurface", userData); if(ptr) set_rcCreateWindowSurface((rcCreateWindowSurface_wrapper_proc_t)ptr);
	ptr = getProc("rcDestroyWindowSurface", userData); if(ptr) set_rcDestroyWindowSurface((rcDestroyWindowSurface_wrapper_proc_t)ptr);
	ptr = getProc("rcCreateColorBuffer", userData); if(ptr) set_rcCreateColorBuffer((rcCreateColorBuffer_wrapper_proc_t)ptr);
	ptr = getProc("rcOpenColorBuffer", userData); if(ptr) set_rcOpenColorBuffer((rcOpenColorBuffer_wrapper_proc_t)ptr);
	ptr = getProc("rcCloseColorBuffer", userData); if(ptr) set_rcCloseColorBuffer((rcCloseColorBuffer_wrapper_proc_t)ptr);
	ptr = getProc("rcSetWindowColorBuffer", userData); if(ptr) set_rcSetWindowColorBuffer((rcSetWindowColorBuffer_wrapper_proc_t)ptr);
	ptr = getProc("rcFlushWindowColorBuffer", userData); if(ptr) set_rcFlushWindowColorBuffer((rcFlushWindowColorBuffer_wrapper_proc_t)ptr);
	ptr = getProc("rcMakeCurrent", userData); if(ptr) set_rcMakeCurrent((rcMakeCurrent_wrapper_proc_t)ptr);
	ptr = getProc("rcFBPost", userData); if(ptr) set_rcFBPost((rcFBPost_wrapper_proc_t)ptr);
	ptr = getProc("rcFBSetSwapInterval", userData); if(ptr) set_rcFBSetSwapInterval((rcFBSetSwapInterval_wrapper_proc_t)ptr);
	ptr = getProc("rcBindTexture", userData); if(ptr) set_rcBindTexture((rcBindTexture_wrapper_proc_t)ptr);
	ptr = getProc("rcBindRenderbuffer", userData); if(ptr) set_rcBindRenderbuffer((rcBindRenderbuffer_wrapper_proc_t)ptr);
	ptr = getProc("rcColorBufferCacheFlush", userData); if(ptr) set_rcColorBufferCacheFlush((rcColorBufferCacheFlush_wrapper_proc_t)ptr);
	ptr = getProc("rcReadColorBuffer", userData); if(ptr) set_rcReadColorBuffer((rcReadColorBuffer_wrapper_proc_t)ptr);
	ptr = getProc("rcUpdateColorBuffer", userData); if(ptr) set_rcUpdateColorBuffer((rcUpdateColorBuffer_wrapper_proc_t)ptr);
	ptr = getProc("rcOpenColorBuffer2", userData); if(ptr) set_rcOpenColorBuffer2((rcOpenColorBuffer2_wrapper_proc_t)ptr);
	ptr = getProc("rcCreateClientImage", userData); if(ptr) set_rcCreateClientImage((rcCreateClientImage_wrapper_proc_t)ptr);
	ptr = getProc("rcDestroyClientImage", userData); if(ptr) set_rcDestroyClientImage((rcDestroyClientImage_wrapper_proc_t)ptr);
	ptr = getProc("rcSelectChecksumHelper", userData); if(ptr) set_rcSelectChecksumHelper((rcSelectChecksumHelper_wrapper_proc_t)ptr);
	ptr = getProc("rcCreateSyncKHR", userData); if(ptr) set_rcCreateSyncKHR((rcCreateSyncKHR_wrapper_proc_t)ptr);
	ptr = getProc("rcClientWaitSyncKHR", userData); if(ptr) set_rcClientWaitSyncKHR((rcClientWaitSyncKHR_wrapper_proc_t)ptr);
	ptr = getProc("rcFlushWindowColorBufferAsync", userData); if(ptr) set_rcFlushWindowColorBufferAsync((rcFlushWindowColorBufferAsync_wrapper_proc_t)ptr);
	ptr = getProc("rcDestroySyncKHR", userData); if(ptr) set_rcDestroySyncKHR((rcDestroySyncKHR_wrapper_proc_t)ptr);
	ptr = getProc("rcSetPuid", userData); if(ptr) set_rcSetPuid((rcSetPuid_wrapper_proc_t)ptr);
	ptr = getProc("rcUpdateColorBufferDMA", userData); if(ptr) set_rcUpdateColorBufferDMA((rcUpdateColorBufferDMA_wrapper_proc_t)ptr);
	ptr = getProc("rcCreateColorBufferDMA", userData); if(ptr) set_rcCreateColorBufferDMA((rcCreateColorBufferDMA_wrapper_proc_t)ptr);
	return 0;
}

