// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __renderControl_wrapper_proc_t_h
#define __renderControl_wrapper_proc_t_h



#include "renderControl_types.h"
#ifndef renderControl_APIENTRY
#define renderControl_APIENTRY 
#endif
typedef GLint (renderControl_APIENTRY *rcGetRendererVersion_wrapper_proc_t) ();
typedef EGLint (renderControl_APIENTRY *rcGetEGLVersion_wrapper_proc_t) (EGLint*, EGLint*);
typedef EGLint (renderControl_APIENTRY *rcQueryEGLString_wrapper_proc_t) (EGLenum, void*, EGLint);
typedef EGLint (renderControl_APIENTRY *rcGetGLString_wrapper_proc_t) (EGLenum, void*, EGLint);
typedef EGLint (renderControl_APIENTRY *rcGetNumConfigs_wrapper_proc_t) (uint32_t*);
typedef EGLint (renderControl_APIENTRY *rcGetConfigs_wrapper_proc_t) (uint32_t, GLuint*);
typedef EGLint (renderControl_APIENTRY *rcChooseConfig_wrapper_proc_t) (EGLint*, uint32_t, uint32_t*, uint32_t);
typedef EGLint (renderControl_APIENTRY *rcGetFBParam_wrapper_proc_t) (EGLint);
typedef uint32_t (renderControl_APIENTRY *rcCreateContext_wrapper_proc_t) (uint32_t, uint32_t, uint32_t);
typedef void (renderControl_APIENTRY *rcDestroyContext_wrapper_proc_t) (uint32_t);
typedef uint32_t (renderControl_APIENTRY *rcCreateWindowSurface_wrapper_proc_t) (uint32_t, uint32_t, uint32_t);
typedef void (renderControl_APIENTRY *rcDestroyWindowSurface_wrapper_proc_t) (uint32_t);
typedef uint32_t (renderControl_APIENTRY *rcCreateColorBuffer_wrapper_proc_t) (uint32_t, uint32_t, GLenum);
typedef void (renderControl_APIENTRY *rcOpenColorBuffer_wrapper_proc_t) (uint32_t);
typedef void (renderControl_APIENTRY *rcCloseColorBuffer_wrapper_proc_t) (uint32_t);
typedef void (renderControl_APIENTRY *rcSetWindowColorBuffer_wrapper_proc_t) (uint32_t, uint32_t);
typedef int (renderControl_APIENTRY *rcFlushWindowColorBuffer_wrapper_proc_t) (uint32_t);
typedef EGLint (renderControl_APIENTRY *rcMakeCurrent_wrapper_proc_t) (uint32_t, uint32_t, uint32_t);
typedef void (renderControl_APIENTRY *rcFBPost_wrapper_proc_t) (uint32_t);
typedef void (renderControl_APIENTRY *rcFBSetSwapInterval_wrapper_proc_t) (EGLint);
typedef void (renderControl_APIENTRY *rcBindTexture_wrapper_proc_t) (uint32_t);
typedef void (renderControl_APIENTRY *rcBindRenderbuffer_wrapper_proc_t) (uint32_t);
typedef EGLint (renderControl_APIENTRY *rcColorBufferCacheFlush_wrapper_proc_t) (uint32_t, EGLint, int);
typedef void (renderControl_APIENTRY *rcReadColorBuffer_wrapper_proc_t) (uint32_t, GLint, GLint, GLint, GLint, GLenum, GLenum, void*);
typedef int (renderControl_APIENTRY *rcUpdateColorBuffer_wrapper_proc_t) (uint32_t, GLint, GLint, GLint, GLint, GLenum, GLenum, void*);
typedef int (renderControl_APIENTRY *rcOpenColorBuffer2_wrapper_proc_t) (uint32_t);
typedef uint32_t (renderControl_APIENTRY *rcCreateClientImage_wrapper_proc_t) (uint32_t, EGLenum, GLuint);
typedef int (renderControl_APIENTRY *rcDestroyClientImage_wrapper_proc_t) (uint32_t);
typedef void (renderControl_APIENTRY *rcSelectChecksumHelper_wrapper_proc_t) (uint32_t, uint32_t);
typedef void (renderControl_APIENTRY *rcCreateSyncKHR_wrapper_proc_t) (EGLenum, EGLint*, uint32_t, int, uint64_t*, uint64_t*);
typedef EGLint (renderControl_APIENTRY *rcClientWaitSyncKHR_wrapper_proc_t) (uint64_t, EGLint, uint64_t);
typedef void (renderControl_APIENTRY *rcFlushWindowColorBufferAsync_wrapper_proc_t) (uint32_t);
typedef int (renderControl_APIENTRY *rcDestroySyncKHR_wrapper_proc_t) (uint64_t);
typedef void (renderControl_APIENTRY *rcSetPuid_wrapper_proc_t) (uint64_t);
typedef int (renderControl_APIENTRY *rcUpdateColorBufferDMA_wrapper_proc_t) (uint32_t, GLint, GLint, GLint, GLint, GLenum, GLenum, void*, uint32_t);
typedef uint32_t (renderControl_APIENTRY *rcCreateColorBufferDMA_wrapper_proc_t) (uint32_t, uint32_t, GLenum, int);


#endif
