// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __renderControl_wrapper_context_t_h
#define __renderControl_wrapper_context_t_h

#include "renderControl_wrapper_proc.h"


struct renderControl_wrapper_context_t {

	rcGetRendererVersion_wrapper_proc_t rcGetRendererVersion;
	rcGetEGLVersion_wrapper_proc_t rcGetEGLVersion;
	rcQueryEGLString_wrapper_proc_t rcQueryEGLString;
	rcGetGLString_wrapper_proc_t rcGetGLString;
	rcGetNumConfigs_wrapper_proc_t rcGetNumConfigs;
	rcGetConfigs_wrapper_proc_t rcGetConfigs;
	rcChooseConfig_wrapper_proc_t rcChooseConfig;
	rcGetFBParam_wrapper_proc_t rcGetFBParam;
	rcCreateContext_wrapper_proc_t rcCreateContext;
	rcDestroyContext_wrapper_proc_t rcDestroyContext;
	rcCreateWindowSurface_wrapper_proc_t rcCreateWindowSurface;
	rcDestroyWindowSurface_wrapper_proc_t rcDestroyWindowSurface;
	rcCreateColorBuffer_wrapper_proc_t rcCreateColorBuffer;
	rcOpenColorBuffer_wrapper_proc_t rcOpenColorBuffer;
	rcCloseColorBuffer_wrapper_proc_t rcCloseColorBuffer;
	rcSetWindowColorBuffer_wrapper_proc_t rcSetWindowColorBuffer;
	rcFlushWindowColorBuffer_wrapper_proc_t rcFlushWindowColorBuffer;
	rcMakeCurrent_wrapper_proc_t rcMakeCurrent;
	rcFBPost_wrapper_proc_t rcFBPost;
	rcFBSetSwapInterval_wrapper_proc_t rcFBSetSwapInterval;
	rcBindTexture_wrapper_proc_t rcBindTexture;
	rcBindRenderbuffer_wrapper_proc_t rcBindRenderbuffer;
	rcColorBufferCacheFlush_wrapper_proc_t rcColorBufferCacheFlush;
	rcReadColorBuffer_wrapper_proc_t rcReadColorBuffer;
	rcUpdateColorBuffer_wrapper_proc_t rcUpdateColorBuffer;
	rcOpenColorBuffer2_wrapper_proc_t rcOpenColorBuffer2;
	rcCreateClientImage_wrapper_proc_t rcCreateClientImage;
	rcDestroyClientImage_wrapper_proc_t rcDestroyClientImage;
	rcSelectChecksumHelper_wrapper_proc_t rcSelectChecksumHelper;
	rcCreateSyncKHR_wrapper_proc_t rcCreateSyncKHR;
	rcClientWaitSyncKHR_wrapper_proc_t rcClientWaitSyncKHR;
	rcFlushWindowColorBufferAsync_wrapper_proc_t rcFlushWindowColorBufferAsync;
	rcDestroySyncKHR_wrapper_proc_t rcDestroySyncKHR;
	rcSetPuid_wrapper_proc_t rcSetPuid;
	rcUpdateColorBufferDMA_wrapper_proc_t rcUpdateColorBufferDMA;
	rcCreateColorBufferDMA_wrapper_proc_t rcCreateColorBufferDMA;
	//Accessors 
	virtual rcGetRendererVersion_wrapper_proc_t set_rcGetRendererVersion(rcGetRendererVersion_wrapper_proc_t f) { rcGetRendererVersion_wrapper_proc_t retval = rcGetRendererVersion; rcGetRendererVersion = f; return retval;}
	virtual rcGetEGLVersion_wrapper_proc_t set_rcGetEGLVersion(rcGetEGLVersion_wrapper_proc_t f) { rcGetEGLVersion_wrapper_proc_t retval = rcGetEGLVersion; rcGetEGLVersion = f; return retval;}
	virtual rcQueryEGLString_wrapper_proc_t set_rcQueryEGLString(rcQueryEGLString_wrapper_proc_t f) { rcQueryEGLString_wrapper_proc_t retval = rcQueryEGLString; rcQueryEGLString = f; return retval;}
	virtual rcGetGLString_wrapper_proc_t set_rcGetGLString(rcGetGLString_wrapper_proc_t f) { rcGetGLString_wrapper_proc_t retval = rcGetGLString; rcGetGLString = f; return retval;}
	virtual rcGetNumConfigs_wrapper_proc_t set_rcGetNumConfigs(rcGetNumConfigs_wrapper_proc_t f) { rcGetNumConfigs_wrapper_proc_t retval = rcGetNumConfigs; rcGetNumConfigs = f; return retval;}
	virtual rcGetConfigs_wrapper_proc_t set_rcGetConfigs(rcGetConfigs_wrapper_proc_t f) { rcGetConfigs_wrapper_proc_t retval = rcGetConfigs; rcGetConfigs = f; return retval;}
	virtual rcChooseConfig_wrapper_proc_t set_rcChooseConfig(rcChooseConfig_wrapper_proc_t f) { rcChooseConfig_wrapper_proc_t retval = rcChooseConfig; rcChooseConfig = f; return retval;}
	virtual rcGetFBParam_wrapper_proc_t set_rcGetFBParam(rcGetFBParam_wrapper_proc_t f) { rcGetFBParam_wrapper_proc_t retval = rcGetFBParam; rcGetFBParam = f; return retval;}
	virtual rcCreateContext_wrapper_proc_t set_rcCreateContext(rcCreateContext_wrapper_proc_t f) { rcCreateContext_wrapper_proc_t retval = rcCreateContext; rcCreateContext = f; return retval;}
	virtual rcDestroyContext_wrapper_proc_t set_rcDestroyContext(rcDestroyContext_wrapper_proc_t f) { rcDestroyContext_wrapper_proc_t retval = rcDestroyContext; rcDestroyContext = f; return retval;}
	virtual rcCreateWindowSurface_wrapper_proc_t set_rcCreateWindowSurface(rcCreateWindowSurface_wrapper_proc_t f) { rcCreateWindowSurface_wrapper_proc_t retval = rcCreateWindowSurface; rcCreateWindowSurface = f; return retval;}
	virtual rcDestroyWindowSurface_wrapper_proc_t set_rcDestroyWindowSurface(rcDestroyWindowSurface_wrapper_proc_t f) { rcDestroyWindowSurface_wrapper_proc_t retval = rcDestroyWindowSurface; rcDestroyWindowSurface = f; return retval;}
	virtual rcCreateColorBuffer_wrapper_proc_t set_rcCreateColorBuffer(rcCreateColorBuffer_wrapper_proc_t f) { rcCreateColorBuffer_wrapper_proc_t retval = rcCreateColorBuffer; rcCreateColorBuffer = f; return retval;}
	virtual rcOpenColorBuffer_wrapper_proc_t set_rcOpenColorBuffer(rcOpenColorBuffer_wrapper_proc_t f) { rcOpenColorBuffer_wrapper_proc_t retval = rcOpenColorBuffer; rcOpenColorBuffer = f; return retval;}
	virtual rcCloseColorBuffer_wrapper_proc_t set_rcCloseColorBuffer(rcCloseColorBuffer_wrapper_proc_t f) { rcCloseColorBuffer_wrapper_proc_t retval = rcCloseColorBuffer; rcCloseColorBuffer = f; return retval;}
	virtual rcSetWindowColorBuffer_wrapper_proc_t set_rcSetWindowColorBuffer(rcSetWindowColorBuffer_wrapper_proc_t f) { rcSetWindowColorBuffer_wrapper_proc_t retval = rcSetWindowColorBuffer; rcSetWindowColorBuffer = f; return retval;}
	virtual rcFlushWindowColorBuffer_wrapper_proc_t set_rcFlushWindowColorBuffer(rcFlushWindowColorBuffer_wrapper_proc_t f) { rcFlushWindowColorBuffer_wrapper_proc_t retval = rcFlushWindowColorBuffer; rcFlushWindowColorBuffer = f; return retval;}
	virtual rcMakeCurrent_wrapper_proc_t set_rcMakeCurrent(rcMakeCurrent_wrapper_proc_t f) { rcMakeCurrent_wrapper_proc_t retval = rcMakeCurrent; rcMakeCurrent = f; return retval;}
	virtual rcFBPost_wrapper_proc_t set_rcFBPost(rcFBPost_wrapper_proc_t f) { rcFBPost_wrapper_proc_t retval = rcFBPost; rcFBPost = f; return retval;}
	virtual rcFBSetSwapInterval_wrapper_proc_t set_rcFBSetSwapInterval(rcFBSetSwapInterval_wrapper_proc_t f) { rcFBSetSwapInterval_wrapper_proc_t retval = rcFBSetSwapInterval; rcFBSetSwapInterval = f; return retval;}
	virtual rcBindTexture_wrapper_proc_t set_rcBindTexture(rcBindTexture_wrapper_proc_t f) { rcBindTexture_wrapper_proc_t retval = rcBindTexture; rcBindTexture = f; return retval;}
	virtual rcBindRenderbuffer_wrapper_proc_t set_rcBindRenderbuffer(rcBindRenderbuffer_wrapper_proc_t f) { rcBindRenderbuffer_wrapper_proc_t retval = rcBindRenderbuffer; rcBindRenderbuffer = f; return retval;}
	virtual rcColorBufferCacheFlush_wrapper_proc_t set_rcColorBufferCacheFlush(rcColorBufferCacheFlush_wrapper_proc_t f) { rcColorBufferCacheFlush_wrapper_proc_t retval = rcColorBufferCacheFlush; rcColorBufferCacheFlush = f; return retval;}
	virtual rcReadColorBuffer_wrapper_proc_t set_rcReadColorBuffer(rcReadColorBuffer_wrapper_proc_t f) { rcReadColorBuffer_wrapper_proc_t retval = rcReadColorBuffer; rcReadColorBuffer = f; return retval;}
	virtual rcUpdateColorBuffer_wrapper_proc_t set_rcUpdateColorBuffer(rcUpdateColorBuffer_wrapper_proc_t f) { rcUpdateColorBuffer_wrapper_proc_t retval = rcUpdateColorBuffer; rcUpdateColorBuffer = f; return retval;}
	virtual rcOpenColorBuffer2_wrapper_proc_t set_rcOpenColorBuffer2(rcOpenColorBuffer2_wrapper_proc_t f) { rcOpenColorBuffer2_wrapper_proc_t retval = rcOpenColorBuffer2; rcOpenColorBuffer2 = f; return retval;}
	virtual rcCreateClientImage_wrapper_proc_t set_rcCreateClientImage(rcCreateClientImage_wrapper_proc_t f) { rcCreateClientImage_wrapper_proc_t retval = rcCreateClientImage; rcCreateClientImage = f; return retval;}
	virtual rcDestroyClientImage_wrapper_proc_t set_rcDestroyClientImage(rcDestroyClientImage_wrapper_proc_t f) { rcDestroyClientImage_wrapper_proc_t retval = rcDestroyClientImage; rcDestroyClientImage = f; return retval;}
	virtual rcSelectChecksumHelper_wrapper_proc_t set_rcSelectChecksumHelper(rcSelectChecksumHelper_wrapper_proc_t f) { rcSelectChecksumHelper_wrapper_proc_t retval = rcSelectChecksumHelper; rcSelectChecksumHelper = f; return retval;}
	virtual rcCreateSyncKHR_wrapper_proc_t set_rcCreateSyncKHR(rcCreateSyncKHR_wrapper_proc_t f) { rcCreateSyncKHR_wrapper_proc_t retval = rcCreateSyncKHR; rcCreateSyncKHR = f; return retval;}
	virtual rcClientWaitSyncKHR_wrapper_proc_t set_rcClientWaitSyncKHR(rcClientWaitSyncKHR_wrapper_proc_t f) { rcClientWaitSyncKHR_wrapper_proc_t retval = rcClientWaitSyncKHR; rcClientWaitSyncKHR = f; return retval;}
	virtual rcFlushWindowColorBufferAsync_wrapper_proc_t set_rcFlushWindowColorBufferAsync(rcFlushWindowColorBufferAsync_wrapper_proc_t f) { rcFlushWindowColorBufferAsync_wrapper_proc_t retval = rcFlushWindowColorBufferAsync; rcFlushWindowColorBufferAsync = f; return retval;}
	virtual rcDestroySyncKHR_wrapper_proc_t set_rcDestroySyncKHR(rcDestroySyncKHR_wrapper_proc_t f) { rcDestroySyncKHR_wrapper_proc_t retval = rcDestroySyncKHR; rcDestroySyncKHR = f; return retval;}
	virtual rcSetPuid_wrapper_proc_t set_rcSetPuid(rcSetPuid_wrapper_proc_t f) { rcSetPuid_wrapper_proc_t retval = rcSetPuid; rcSetPuid = f; return retval;}
	virtual rcUpdateColorBufferDMA_wrapper_proc_t set_rcUpdateColorBufferDMA(rcUpdateColorBufferDMA_wrapper_proc_t f) { rcUpdateColorBufferDMA_wrapper_proc_t retval = rcUpdateColorBufferDMA; rcUpdateColorBufferDMA = f; return retval;}
	virtual rcCreateColorBufferDMA_wrapper_proc_t set_rcCreateColorBufferDMA(rcCreateColorBufferDMA_wrapper_proc_t f) { rcCreateColorBufferDMA_wrapper_proc_t retval = rcCreateColorBufferDMA; rcCreateColorBufferDMA = f; return retval;}
	 virtual ~renderControl_wrapper_context_t() {}

	typedef renderControl_wrapper_context_t *CONTEXT_ACCESSOR_TYPE(void);
	static void setContextAccessor(CONTEXT_ACCESSOR_TYPE *f);
	int initDispatchByName( void *(*getProc)(const char *name, void *userData), void *userData);
};

#endif
