// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#include <stdio.h>
#include <stdlib.h>
#include "gles1_wrapper_context.h"
#include "ErrorLog.h"

#include "gles1_entry.cpp"
#include <sys/mman.h>
#define VALID_PTR(ptr) (mprotect(ptr,1,PROT_READ|PROT_WRITE)==-1)
#define VALID_PARAMETER(ptr) ((unsigned int)ptr<=0x400000)
#ifndef GLsync
typedef struct __GLsync *GLsync;
#endif


#ifndef GL_TRUE
extern "C" {
	void glAlphaFunc(GLenum func, GLclampf ref);
	void glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
	void glClearDepthf(GLclampf depth);
	void glClipPlanef(GLenum plane, const GLfloat* equation);
	void glColor4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
	void glDepthRangef(GLclampf zNear, GLclampf zFar);
	void glFogf(GLenum pname, GLfloat param);
	void glFogfv(GLenum pname, const GLfloat* params);
	void glFrustumf(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar);
	void glGetClipPlanef(GLenum pname, GLfloat* eqn);
	void glGetFloatv(GLenum pname, GLfloat* params);
	void glGetLightfv(GLenum light, GLenum pname, GLfloat* params);
	void glGetMaterialfv(GLenum face, GLenum pname, GLfloat* params);
	void glGetTexEnvfv(GLenum env, GLenum pname, GLfloat* params);
	void glGetTexParameterfv(GLenum target, GLenum pname, GLfloat* params);
	void glLightModelf(GLenum pname, GLfloat param);
	void glLightModelfv(GLenum pname, const GLfloat* params);
	void glLightf(GLenum light, GLenum pname, GLfloat param);
	void glLightfv(GLenum light, GLenum pname, const GLfloat* params);
	void glLineWidth(GLfloat width);
	void glLoadMatrixf(const GLfloat* m);
	void glMaterialf(GLenum face, GLenum pname, GLfloat param);
	void glMaterialfv(GLenum face, GLenum pname, const GLfloat* params);
	void glMultMatrixf(const GLfloat* m);
	void glMultiTexCoord4f(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
	void glNormal3f(GLfloat nx, GLfloat ny, GLfloat nz);
	void glOrthof(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar);
	void glPointParameterf(GLenum pname, GLfloat param);
	void glPointParameterfv(GLenum pname, const GLfloat* params);
	void glPointSize(GLfloat size);
	void glPolygonOffset(GLfloat factor, GLfloat units);
	void glRotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
	void glScalef(GLfloat x, GLfloat y, GLfloat z);
	void glTexEnvf(GLenum target, GLenum pname, GLfloat param);
	void glTexEnvfv(GLenum target, GLenum pname, const GLfloat* params);
	void glTexParameterf(GLenum target, GLenum pname, GLfloat param);
	void glTexParameterfv(GLenum target, GLenum pname, const GLfloat* params);
	void glTranslatef(GLfloat x, GLfloat y, GLfloat z);
	void glActiveTexture(GLenum texture);
	void glAlphaFuncx(GLenum func, GLclampx ref);
	void glBindBuffer(GLenum target, GLuint buffer);
	void glBindTexture(GLenum target, GLuint texture);
	void glBlendFunc(GLenum sfactor, GLenum dfactor);
	void glBufferData(GLenum target, GLsizeiptr size, const GLvoid* data, GLenum usage);
	void glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid* data);
	void glClear(GLbitfield mask);
	void glClearColorx(GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha);
	void glClearDepthx(GLclampx depth);
	void glClearStencil(GLint s);
	void glClientActiveTexture(GLenum texture);
	void glColor4ub(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
	void glColor4x(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha);
	void glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
	void glColorPointer(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
	void glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid* data);
	void glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid* data);
	void glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
	void glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
	void glCullFace(GLenum mode);
	void glDeleteBuffers(GLsizei n, const GLuint* buffers);
	void glDeleteTextures(GLsizei n, const GLuint* textures);
	void glDepthFunc(GLenum func);
	void glDepthMask(GLboolean flag);
	void glDepthRangex(GLclampx zNear, GLclampx zFar);
	void glDisable(GLenum cap);
	void glDisableClientState(GLenum array);
	void glDrawArrays(GLenum mode, GLint first, GLsizei count);
	void glDrawElements(GLenum mode, GLsizei count, GLenum type, const GLvoid* indices);
	void glEnable(GLenum cap);
	void glEnableClientState(GLenum array);
	void glFinish();
	void glFlush();
	void glFogx(GLenum pname, GLfixed param);
	void glFogxv(GLenum pname, const GLfixed* params);
	void glFrontFace(GLenum mode);
	void glFrustumx(GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar);
	void glGetBooleanv(GLenum pname, GLboolean* params);
	void glGetBufferParameteriv(GLenum target, GLenum pname, GLint* params);
	void glClipPlanex(GLenum pname, const GLfixed* eqn);
	void glGenBuffers(GLsizei n, GLuint* buffers);
	void glGenTextures(GLsizei n, GLuint* textures);
	GLenum glGetError();
	void glGetFixedv(GLenum pname, GLfixed* params);
	void glGetIntegerv(GLenum pname, GLint* params);
	void glGetLightxv(GLenum light, GLenum pname, GLfixed* params);
	void glGetMaterialxv(GLenum face, GLenum pname, GLfixed* params);
	void glGetPointerv(GLenum pname, GLvoid** params);
	const GLubyte* glGetString(GLenum name);
	void glGetTexEnviv(GLenum env, GLenum pname, GLint* params);
	void glGetTexEnvxv(GLenum env, GLenum pname, GLfixed* params);
	void glGetTexParameteriv(GLenum target, GLenum pname, GLint* params);
	void glGetTexParameterxv(GLenum target, GLenum pname, GLfixed* params);
	void glHint(GLenum target, GLenum mode);
	GLboolean glIsBuffer(GLuint buffer);
	GLboolean glIsEnabled(GLenum cap);
	GLboolean glIsTexture(GLuint texture);
	void glLightModelx(GLenum pname, GLfixed param);
	void glLightModelxv(GLenum pname, const GLfixed* params);
	void glLightx(GLenum light, GLenum pname, GLfixed param);
	void glLightxv(GLenum light, GLenum pname, const GLfixed* params);
	void glLineWidthx(GLfixed width);
	void glLoadIdentity();
	void glLoadMatrixx(const GLfixed* m);
	void glLogicOp(GLenum opcode);
	void glMaterialx(GLenum face, GLenum pname, GLfixed param);
	void glMaterialxv(GLenum face, GLenum pname, const GLfixed* params);
	void glMatrixMode(GLenum mode);
	void glMultMatrixx(const GLfixed* m);
	void glMultiTexCoord4x(GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q);
	void glNormal3x(GLfixed nx, GLfixed ny, GLfixed nz);
	void glNormalPointer(GLenum type, GLsizei stride, const GLvoid* pointer);
	void glOrthox(GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar);
	void glPixelStorei(GLenum pname, GLint param);
	void glPointParameterx(GLenum pname, GLfixed param);
	void glPointParameterxv(GLenum pname, const GLfixed* params);
	void glPointSizex(GLfixed size);
	void glPolygonOffsetx(GLfixed factor, GLfixed units);
	void glPopMatrix();
	void glPushMatrix();
	void glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels);
	void glRotatex(GLfixed angle, GLfixed x, GLfixed y, GLfixed z);
	void glSampleCoverage(GLclampf value, GLboolean invert);
	void glSampleCoveragex(GLclampx value, GLboolean invert);
	void glScalex(GLfixed x, GLfixed y, GLfixed z);
	void glScissor(GLint x, GLint y, GLsizei width, GLsizei height);
	void glShadeModel(GLenum mode);
	void glStencilFunc(GLenum func, GLint ref, GLuint mask);
	void glStencilMask(GLuint mask);
	void glStencilOp(GLenum fail, GLenum zfail, GLenum zpass);
	void glTexCoordPointer(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
	void glTexEnvi(GLenum target, GLenum pname, GLint param);
	void glTexEnvx(GLenum target, GLenum pname, GLfixed param);
	void glTexEnviv(GLenum target, GLenum pname, const GLint* params);
	void glTexEnvxv(GLenum target, GLenum pname, const GLfixed* params);
	void glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid* pixels);
	void glTexParameteri(GLenum target, GLenum pname, GLint param);
	void glTexParameterx(GLenum target, GLenum pname, GLfixed param);
	void glTexParameteriv(GLenum target, GLenum pname, const GLint* params);
	void glTexParameterxv(GLenum target, GLenum pname, const GLfixed* params);
	void glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid* pixels);
	void glTranslatex(GLfixed x, GLfixed y, GLfixed z);
	void glVertexPointer(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
	void glViewport(GLint x, GLint y, GLsizei width, GLsizei height);
	void glPointSizePointerOES(GLenum type, GLsizei stride, const GLvoid* pointer);
	void glVertexPointerOffset(GLint size, GLenum type, GLsizei stride, GLuint offset);
	void glColorPointerOffset(GLint size, GLenum type, GLsizei stride, GLuint offset);
	void glNormalPointerOffset(GLenum type, GLsizei stride, GLuint offset);
	void glPointSizePointerOffset(GLenum type, GLsizei stride, GLuint offset);
	void glTexCoordPointerOffset(GLint size, GLenum type, GLsizei stride, GLuint offset);
	void glWeightPointerOffset(GLint size, GLenum type, GLsizei stride, GLuint offset);
	void glMatrixIndexPointerOffset(GLint size, GLenum type, GLsizei stride, GLuint offset);
	void glVertexPointerData(GLint size, GLenum type, GLsizei stride, void* data, GLuint datalen);
	void glColorPointerData(GLint size, GLenum type, GLsizei stride, void* data, GLuint datalen);
	void glNormalPointerData(GLenum type, GLsizei stride, void* data, GLuint datalen);
	void glTexCoordPointerData(GLint unit, GLint size, GLenum type, GLsizei stride, void* data, GLuint datalen);
	void glPointSizePointerData(GLenum type, GLsizei stride, void* data, GLuint datalen);
	void glWeightPointerData(GLint size, GLenum type, GLsizei stride, void* data, GLuint datalen);
	void glMatrixIndexPointerData(GLint size, GLenum type, GLsizei stride, void* data, GLuint datalen);
	void glDrawElementsOffset(GLenum mode, GLsizei count, GLenum type, GLuint offset);
	void glDrawElementsData(GLenum mode, GLsizei count, GLenum type, void* data, GLuint datalen);
	void glGetCompressedTextureFormats(int count, GLint* formats);
	int glFinishRoundTrip();
	void glBlendEquationSeparateOES(GLenum modeRGB, GLenum modeAlpha);
	void glBlendFuncSeparateOES(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
	void glBlendEquationOES(GLenum mode);
	void glDrawTexsOES(GLshort x, GLshort y, GLshort z, GLshort width, GLshort height);
	void glDrawTexiOES(GLint x, GLint y, GLint z, GLint width, GLint height);
	void glDrawTexxOES(GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height);
	void glDrawTexsvOES(const GLshort* coords);
	void glDrawTexivOES(const GLint* coords);
	void glDrawTexxvOES(const GLfixed* coords);
	void glDrawTexfOES(GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height);
	void glDrawTexfvOES(const GLfloat* coords);
	void glEGLImageTargetTexture2DOES(GLenum target, GLeglImageOES image);
	void glEGLImageTargetRenderbufferStorageOES(GLenum target, GLeglImageOES image);
	void glAlphaFuncxOES(GLenum func, GLclampx ref);
	void glClearColorxOES(GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha);
	void glClearDepthxOES(GLclampx depth);
	void glClipPlanexOES(GLenum plane, const GLfixed* equation);
	void glClipPlanexIMG(GLenum plane, const GLfixed* equation);
	void glColor4xOES(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha);
	void glDepthRangexOES(GLclampx zNear, GLclampx zFar);
	void glFogxOES(GLenum pname, GLfixed param);
	void glFogxvOES(GLenum pname, const GLfixed* params);
	void glFrustumxOES(GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar);
	void glGetClipPlanexOES(GLenum pname, GLfixed* eqn);
	void glGetClipPlanex(GLenum pname, GLfixed* eqn);
	void glGetFixedvOES(GLenum pname, GLfixed* params);
	void glGetLightxvOES(GLenum light, GLenum pname, GLfixed* params);
	void glGetMaterialxvOES(GLenum face, GLenum pname, GLfixed* params);
	void glGetTexEnvxvOES(GLenum env, GLenum pname, GLfixed* params);
	void glGetTexParameterxvOES(GLenum target, GLenum pname, GLfixed* params);
	void glLightModelxOES(GLenum pname, GLfixed param);
	void glLightModelxvOES(GLenum pname, const GLfixed* params);
	void glLightxOES(GLenum light, GLenum pname, GLfixed param);
	void glLightxvOES(GLenum light, GLenum pname, const GLfixed* params);
	void glLineWidthxOES(GLfixed width);
	void glLoadMatrixxOES(const GLfixed* m);
	void glMaterialxOES(GLenum face, GLenum pname, GLfixed param);
	void glMaterialxvOES(GLenum face, GLenum pname, const GLfixed* params);
	void glMultMatrixxOES(const GLfixed* m);
	void glMultiTexCoord4xOES(GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q);
	void glNormal3xOES(GLfixed nx, GLfixed ny, GLfixed nz);
	void glOrthoxOES(GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar);
	void glPointParameterxOES(GLenum pname, GLfixed param);
	void glPointParameterxvOES(GLenum pname, const GLfixed* params);
	void glPointSizexOES(GLfixed size);
	void glPolygonOffsetxOES(GLfixed factor, GLfixed units);
	void glRotatexOES(GLfixed angle, GLfixed x, GLfixed y, GLfixed z);
	void glSampleCoveragexOES(GLclampx value, GLboolean invert);
	void glScalexOES(GLfixed x, GLfixed y, GLfixed z);
	void glTexEnvxOES(GLenum target, GLenum pname, GLfixed param);
	void glTexEnvxvOES(GLenum target, GLenum pname, const GLfixed* params);
	void glTexParameterxOES(GLenum target, GLenum pname, GLfixed param);
	void glTexParameterxvOES(GLenum target, GLenum pname, const GLfixed* params);
	void glTranslatexOES(GLfixed x, GLfixed y, GLfixed z);
	GLboolean glIsRenderbufferOES(GLuint renderbuffer);
	void glBindRenderbufferOES(GLenum target, GLuint renderbuffer);
	void glDeleteRenderbuffersOES(GLsizei n, const GLuint* renderbuffers);
	void glGenRenderbuffersOES(GLsizei n, GLuint* renderbuffers);
	void glRenderbufferStorageOES(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
	void glGetRenderbufferParameterivOES(GLenum target, GLenum pname, GLint* params);
	GLboolean glIsFramebufferOES(GLuint framebuffer);
	void glBindFramebufferOES(GLenum target, GLuint framebuffer);
	void glDeleteFramebuffersOES(GLsizei n, const GLuint* framebuffers);
	void glGenFramebuffersOES(GLsizei n, GLuint* framebuffers);
	GLenum glCheckFramebufferStatusOES(GLenum target);
	void glFramebufferRenderbufferOES(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
	void glFramebufferTexture2DOES(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
	void glGetFramebufferAttachmentParameterivOES(GLenum target, GLenum attachment, GLenum pname, GLint* params);
	void glGenerateMipmapOES(GLenum target);
	void* glMapBufferOES(GLenum target, GLenum access);
	GLboolean glUnmapBufferOES(GLenum target);
	void glGetBufferPointervOES(GLenum target, GLenum pname, GLvoid** params);
	void glCurrentPaletteMatrixOES(GLuint matrixpaletteindex);
	void glLoadPaletteFromModelViewMatrixOES();
	void glMatrixIndexPointerOES(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
	void glWeightPointerOES(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
	GLbitfield glQueryMatrixxOES(GLfixed* mantissa, GLint* exponent);
	void glDepthRangefOES(GLclampf zNear, GLclampf zFar);
	void glFrustumfOES(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar);
	void glOrthofOES(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar);
	void glClipPlanefOES(GLenum plane, const GLfloat* equation);
	void glClipPlanefIMG(GLenum plane, const GLfloat* equation);
	void glGetClipPlanefOES(GLenum pname, GLfloat* eqn);
	void glClearDepthfOES(GLclampf depth);
	void glTexGenfOES(GLenum coord, GLenum pname, GLfloat param);
	void glTexGenfvOES(GLenum coord, GLenum pname, const GLfloat* params);
	void glTexGeniOES(GLenum coord, GLenum pname, GLint param);
	void glTexGenivOES(GLenum coord, GLenum pname, const GLint* params);
	void glTexGenxOES(GLenum coord, GLenum pname, GLfixed param);
	void glTexGenxvOES(GLenum coord, GLenum pname, const GLfixed* params);
	void glGetTexGenfvOES(GLenum coord, GLenum pname, GLfloat* params);
	void glGetTexGenivOES(GLenum coord, GLenum pname, GLint* params);
	void glGetTexGenxvOES(GLenum coord, GLenum pname, GLfixed* params);
	void glBindVertexArrayOES(GLuint array);
	void glDeleteVertexArraysOES(GLsizei n, const GLuint* arrays);
	void glGenVertexArraysOES(GLsizei n, GLuint* arrays);
	GLboolean glIsVertexArrayOES(GLuint array);
	void glDiscardFramebufferEXT(GLenum target, GLsizei numAttachments, const GLenum* attachments);
	void glMultiDrawArraysEXT(GLenum mode, const GLint* first, const GLsizei* count, GLsizei primcount);
	void glMultiDrawElementsEXT(GLenum mode, const GLsizei* count, GLenum type, const GLvoid*const* indices, GLsizei primcount);
	void glMultiDrawArraysSUN(GLenum mode, GLint* first, GLsizei* count, GLsizei primcount);
	void glMultiDrawElementsSUN(GLenum mode, const GLsizei* count, GLenum type, const GLvoid** indices, GLsizei primcount);
	void glRenderbufferStorageMultisampleIMG(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
	void glFramebufferTexture2DMultisampleIMG(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLsizei samples);
	void glDeleteFencesNV(GLsizei n, const GLuint* fences);
	void glGenFencesNV(GLsizei n, GLuint* fences);
	GLboolean glIsFenceNV(GLuint fence);
	GLboolean glTestFenceNV(GLuint fence);
	void glGetFenceivNV(GLuint fence, GLenum pname, GLint* params);
	void glFinishFenceNV(GLuint fence);
	void glSetFenceNV(GLuint fence, GLenum condition);
	void glGetDriverControlsQCOM(GLint* num, GLsizei size, GLuint* driverControls);
	void glGetDriverControlStringQCOM(GLuint driverControl, GLsizei bufSize, GLsizei* length, GLchar* driverControlString);
	void glEnableDriverControlQCOM(GLuint driverControl);
	void glDisableDriverControlQCOM(GLuint driverControl);
	void glExtGetTexturesQCOM(GLuint* textures, GLint maxTextures, GLint* numTextures);
	void glExtGetBuffersQCOM(GLuint* buffers, GLint maxBuffers, GLint* numBuffers);
	void glExtGetRenderbuffersQCOM(GLuint* renderbuffers, GLint maxRenderbuffers, GLint* numRenderbuffers);
	void glExtGetFramebuffersQCOM(GLuint* framebuffers, GLint maxFramebuffers, GLint* numFramebuffers);
	void glExtGetTexLevelParameterivQCOM(GLuint texture, GLenum face, GLint level, GLenum pname, GLint* params);
	void glExtTexObjectStateOverrideiQCOM(GLenum target, GLenum pname, GLint param);
	void glExtGetTexSubImageQCOM(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLvoid* texels);
	void glExtGetBufferPointervQCOM(GLenum target, GLvoid** params);
	void glExtGetShadersQCOM(GLuint* shaders, GLint maxShaders, GLint* numShaders);
	void glExtGetProgramsQCOM(GLuint* programs, GLint maxPrograms, GLint* numPrograms);
	GLboolean glExtIsProgramBinaryQCOM(GLuint program);
	void glExtGetProgramBinarySourceQCOM(GLuint program, GLenum shadertype, GLchar* source, GLint* length);
	void glStartTilingQCOM(GLuint x, GLuint y, GLuint width, GLuint height, GLbitfield preserveMask);
	void glEndTilingQCOM(GLbitfield preserveMask);
};

#endif


#undef GET_CONTEXT_wrapper
#ifndef GET_CONTEXT_wrapper
static gles1_wrapper_context_t::CONTEXT_ACCESSOR_TYPE *getCurrentContext_wrapper = NULL;
void gles1_wrapper_context_t::setContextAccessor(CONTEXT_ACCESSOR_TYPE *f) { getCurrentContext_wrapper = f; }
#define GET_CONTEXT_wrapper gles1_wrapper_context_t * ctx = getCurrentContext_wrapper() 
#endif

void glAlphaFunc(GLenum func, GLclampf ref)
{
	RedFinger_glAlphaFunc( func, ref);
}

void glClearColor(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
{
	RedFinger_glClearColor( red, green, blue, alpha);
}

void glClearDepthf(GLclampf depth)
{
	RedFinger_glClearDepthf( depth);
}

void glClipPlanef(GLenum plane, const GLfloat* equation)
{
	RedFinger_glClipPlanef( plane, equation);
}

void glColor4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
{
	RedFinger_glColor4f( red, green, blue, alpha);
}

void glDepthRangef(GLclampf zNear, GLclampf zFar)
{
	RedFinger_glDepthRangef( zNear, zFar);
}

void glFogf(GLenum pname, GLfloat param)
{
	RedFinger_glFogf( pname, param);
}

void glFogfv(GLenum pname, const GLfloat* params)
{
	RedFinger_glFogfv( pname, params);
}

void glFrustumf(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
{
	RedFinger_glFrustumf( left, right, bottom, top, zNear, zFar);
}

void glGetClipPlanef(GLenum pname, GLfloat* eqn)
{
	RedFinger_glGetClipPlanef( pname, eqn);
}

void glGetFloatv(GLenum pname, GLfloat* params)
{
	RedFinger_glGetFloatv( pname, params);
}

void glGetLightfv(GLenum light, GLenum pname, GLfloat* params)
{
	RedFinger_glGetLightfv( light, pname, params);
}

void glGetMaterialfv(GLenum face, GLenum pname, GLfloat* params)
{
	RedFinger_glGetMaterialfv( face, pname, params);
}

void glGetTexEnvfv(GLenum env, GLenum pname, GLfloat* params)
{
	RedFinger_glGetTexEnvfv( env, pname, params);
}

void glGetTexParameterfv(GLenum target, GLenum pname, GLfloat* params)
{
	RedFinger_glGetTexParameterfv( target, pname, params);
}

void glLightModelf(GLenum pname, GLfloat param)
{
	RedFinger_glLightModelf( pname, param);
}

void glLightModelfv(GLenum pname, const GLfloat* params)
{
	RedFinger_glLightModelfv( pname, params);
}

void glLightf(GLenum light, GLenum pname, GLfloat param)
{
	RedFinger_glLightf( light, pname, param);
}

void glLightfv(GLenum light, GLenum pname, const GLfloat* params)
{
	RedFinger_glLightfv( light, pname, params);
}

void glLineWidth(GLfloat width)
{
	RedFinger_glLineWidth( width);
}

void glLoadMatrixf(const GLfloat* m)
{
	RedFinger_glLoadMatrixf( m);
}

void glMaterialf(GLenum face, GLenum pname, GLfloat param)
{
	RedFinger_glMaterialf( face, pname, param);
}

void glMaterialfv(GLenum face, GLenum pname, const GLfloat* params)
{
	RedFinger_glMaterialfv( face, pname, params);
}

void glMultMatrixf(const GLfloat* m)
{
	RedFinger_glMultMatrixf( m);
}

void glMultiTexCoord4f(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
{
	RedFinger_glMultiTexCoord4f( target, s, t, r, q);
}

void glNormal3f(GLfloat nx, GLfloat ny, GLfloat nz)
{
	RedFinger_glNormal3f( nx, ny, nz);
}

void glOrthof(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
{
	RedFinger_glOrthof( left, right, bottom, top, zNear, zFar);
}

void glPointParameterf(GLenum pname, GLfloat param)
{
	RedFinger_glPointParameterf( pname, param);
}

void glPointParameterfv(GLenum pname, const GLfloat* params)
{
	RedFinger_glPointParameterfv( pname, params);
}

void glPointSize(GLfloat size)
{
	RedFinger_glPointSize( size);
}

void glPolygonOffset(GLfloat factor, GLfloat units)
{
	RedFinger_glPolygonOffset( factor, units);
}

void glRotatef(GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
{
	RedFinger_glRotatef( angle, x, y, z);
}

void glScalef(GLfloat x, GLfloat y, GLfloat z)
{
	RedFinger_glScalef( x, y, z);
}

void glTexEnvf(GLenum target, GLenum pname, GLfloat param)
{
	RedFinger_glTexEnvf( target, pname, param);
}

void glTexEnvfv(GLenum target, GLenum pname, const GLfloat* params)
{
	RedFinger_glTexEnvfv( target, pname, params);
}

void glTexParameterf(GLenum target, GLenum pname, GLfloat param)
{
	RedFinger_glTexParameterf( target, pname, param);
}

void glTexParameterfv(GLenum target, GLenum pname, const GLfloat* params)
{
	RedFinger_glTexParameterfv( target, pname, params);
}

void glTranslatef(GLfloat x, GLfloat y, GLfloat z)
{
	RedFinger_glTranslatef( x, y, z);
}

void glActiveTexture(GLenum texture)
{
	RedFinger_glActiveTexture( texture);
}

void glAlphaFuncx(GLenum func, GLclampx ref)
{
	RedFinger_glAlphaFuncx( func, ref);
}

void glBindBuffer(GLenum target, GLuint buffer)
{
	RedFinger_glBindBuffer( target, buffer);
}

void glBindTexture(GLenum target, GLuint texture)
{
	RedFinger_glBindTexture( target, texture);
}

void glBlendFunc(GLenum sfactor, GLenum dfactor)
{
	RedFinger_glBlendFunc( sfactor, dfactor);
}

void glBufferData(GLenum target, GLsizeiptr size, const GLvoid* data, GLenum usage)
{
	RedFinger_glBufferData( target, size, data, usage);
}

void glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid* data)
{
	RedFinger_glBufferSubData( target, offset, size, data);
}

void glClear(GLbitfield mask)
{
	RedFinger_glClear( mask);
}

void glClearColorx(GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
{
	RedFinger_glClearColorx( red, green, blue, alpha);
}

void glClearDepthx(GLclampx depth)
{
	RedFinger_glClearDepthx( depth);
}

void glClearStencil(GLint s)
{
	RedFinger_glClearStencil( s);
}

void glClientActiveTexture(GLenum texture)
{
	RedFinger_glClientActiveTexture( texture);
}

void glColor4ub(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
{
	RedFinger_glColor4ub( red, green, blue, alpha);
}

void glColor4x(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
{
	RedFinger_glColor4x( red, green, blue, alpha);
}

void glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
{
	RedFinger_glColorMask( red, green, blue, alpha);
}

void glColorPointer(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer)
{
	RedFinger_glColorPointer( size, type, stride, pointer);
}

void glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid* data)
{
	RedFinger_glCompressedTexImage2D( target, level, internalformat, width, height, border, imageSize, data);
}

void glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid* data)
{
	RedFinger_glCompressedTexSubImage2D( target, level, xoffset, yoffset, width, height, format, imageSize, data);
}

void glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
{
	RedFinger_glCopyTexImage2D( target, level, internalformat, x, y, width, height, border);
}

void glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
{
	RedFinger_glCopyTexSubImage2D( target, level, xoffset, yoffset, x, y, width, height);
}

void glCullFace(GLenum mode)
{
	RedFinger_glCullFace( mode);
}

void glDeleteBuffers(GLsizei n, const GLuint* buffers)
{
	RedFinger_glDeleteBuffers( n, buffers);
}

void glDeleteTextures(GLsizei n, const GLuint* textures)
{
	RedFinger_glDeleteTextures( n, textures);
}

void glDepthFunc(GLenum func)
{
	RedFinger_glDepthFunc( func);
}

void glDepthMask(GLboolean flag)
{
	RedFinger_glDepthMask( flag);
}

void glDepthRangex(GLclampx zNear, GLclampx zFar)
{
	RedFinger_glDepthRangex( zNear, zFar);
}

void glDisable(GLenum cap)
{
	RedFinger_glDisable( cap);
}

void glDisableClientState(GLenum array)
{
	RedFinger_glDisableClientState( array);
}

void glDrawArrays(GLenum mode, GLint first, GLsizei count)
{
	RedFinger_glDrawArrays( mode, first, count);
}

void glDrawElements(GLenum mode, GLsizei count, GLenum type, const GLvoid* indices)
{
	RedFinger_glDrawElements( mode, count, type, indices);
}

void glEnable(GLenum cap)
{
	RedFinger_glEnable( cap);
}

void glEnableClientState(GLenum array)
{
	RedFinger_glEnableClientState( array);
}

void glFinish()
{
	RedFinger_glFinish();
}

void glFlush()
{
	RedFinger_glFlush();
}

void glFogx(GLenum pname, GLfixed param)
{
	RedFinger_glFogx( pname, param);
}

void glFogxv(GLenum pname, const GLfixed* params)
{
	RedFinger_glFogxv( pname, params);
}

void glFrontFace(GLenum mode)
{
	RedFinger_glFrontFace( mode);
}

void glFrustumx(GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
{
	RedFinger_glFrustumx( left, right, bottom, top, zNear, zFar);
}

void glGetBooleanv(GLenum pname, GLboolean* params)
{
	RedFinger_glGetBooleanv( pname, params);
}

void glGetBufferParameteriv(GLenum target, GLenum pname, GLint* params)
{
	RedFinger_glGetBufferParameteriv( target, pname, params);
}

void glClipPlanex(GLenum pname, const GLfixed* eqn)
{
	RedFinger_glClipPlanex( pname, eqn);
}

void glGenBuffers(GLsizei n, GLuint* buffers)
{
	RedFinger_glGenBuffers( n, buffers);
}

void glGenTextures(GLsizei n, GLuint* textures)
{
	RedFinger_glGenTextures( n, textures);
}

GLenum glGetError()
{
	return RedFinger_glGetError();
}

void glGetFixedv(GLenum pname, GLfixed* params)
{
	RedFinger_glGetFixedv( pname, params);
}

void glGetIntegerv(GLenum pname, GLint* params)
{
	RedFinger_glGetIntegerv( pname, params);
}

void glGetLightxv(GLenum light, GLenum pname, GLfixed* params)
{
	RedFinger_glGetLightxv( light, pname, params);
}

void glGetMaterialxv(GLenum face, GLenum pname, GLfixed* params)
{
	RedFinger_glGetMaterialxv( face, pname, params);
}

void glGetPointerv(GLenum pname, GLvoid** params)
{
	ALOGD("run function:%s,%d\n",__func__,__LINE__);
	GET_CONTEXT_wrapper; 
	 ctx->glGetPointerv( pname, params);
}

const GLubyte* glGetString(GLenum name)
{
	return RedFinger_glGetString( name);
}

void glGetTexEnviv(GLenum env, GLenum pname, GLint* params)
{
	RedFinger_glGetTexEnviv( env, pname, params);
}

void glGetTexEnvxv(GLenum env, GLenum pname, GLfixed* params)
{
	RedFinger_glGetTexEnvxv( env, pname, params);
}

void glGetTexParameteriv(GLenum target, GLenum pname, GLint* params)
{
	RedFinger_glGetTexParameteriv( target, pname, params);
}

void glGetTexParameterxv(GLenum target, GLenum pname, GLfixed* params)
{
	RedFinger_glGetTexParameterxv( target, pname, params);
}

void glHint(GLenum target, GLenum mode)
{
	RedFinger_glHint( target, mode);
}

GLboolean glIsBuffer(GLuint buffer)
{
	return RedFinger_glIsBuffer( buffer);
}

GLboolean glIsEnabled(GLenum cap)
{
	return RedFinger_glIsEnabled( cap);
}

GLboolean glIsTexture(GLuint texture)
{
	return RedFinger_glIsTexture( texture);
}

void glLightModelx(GLenum pname, GLfixed param)
{
	RedFinger_glLightModelx( pname, param);
}

void glLightModelxv(GLenum pname, const GLfixed* params)
{
	RedFinger_glLightModelxv( pname, params);
}

void glLightx(GLenum light, GLenum pname, GLfixed param)
{
	RedFinger_glLightx( light, pname, param);
}

void glLightxv(GLenum light, GLenum pname, const GLfixed* params)
{
	RedFinger_glLightxv( light, pname, params);
}

void glLineWidthx(GLfixed width)
{
	RedFinger_glLineWidthx( width);
}

void glLoadIdentity()
{
	RedFinger_glLoadIdentity();
}

void glLoadMatrixx(const GLfixed* m)
{
	RedFinger_glLoadMatrixx( m);
}

void glLogicOp(GLenum opcode)
{
	RedFinger_glLogicOp( opcode);
}

void glMaterialx(GLenum face, GLenum pname, GLfixed param)
{
	RedFinger_glMaterialx( face, pname, param);
}

void glMaterialxv(GLenum face, GLenum pname, const GLfixed* params)
{
	RedFinger_glMaterialxv( face, pname, params);
}

void glMatrixMode(GLenum mode)
{
	RedFinger_glMatrixMode( mode);
}

void glMultMatrixx(const GLfixed* m)
{
	RedFinger_glMultMatrixx( m);
}

void glMultiTexCoord4x(GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
{
	RedFinger_glMultiTexCoord4x( target, s, t, r, q);
}

void glNormal3x(GLfixed nx, GLfixed ny, GLfixed nz)
{
	RedFinger_glNormal3x( nx, ny, nz);
}

void glNormalPointer(GLenum type, GLsizei stride, const GLvoid* pointer)
{
	RedFinger_glNormalPointer( type, stride, pointer);
}

void glOrthox(GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
{
	RedFinger_glOrthox( left, right, bottom, top, zNear, zFar);
}

void glPixelStorei(GLenum pname, GLint param)
{
	RedFinger_glPixelStorei( pname, param);
}

void glPointParameterx(GLenum pname, GLfixed param)
{
	RedFinger_glPointParameterx( pname, param);
}

void glPointParameterxv(GLenum pname, const GLfixed* params)
{
	RedFinger_glPointParameterxv( pname, params);
}

void glPointSizex(GLfixed size)
{
	RedFinger_glPointSizex( size);
}

void glPolygonOffsetx(GLfixed factor, GLfixed units)
{
	RedFinger_glPolygonOffsetx( factor, units);
}

void glPopMatrix()
{
	RedFinger_glPopMatrix();
}

void glPushMatrix()
{
	RedFinger_glPushMatrix();
}

void glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels)
{
	RedFinger_glReadPixels( x, y, width, height, format, type, pixels);
}

void glRotatex(GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
{
	RedFinger_glRotatex( angle, x, y, z);
}

void glSampleCoverage(GLclampf value, GLboolean invert)
{
	RedFinger_glSampleCoverage( value, invert);
}

void glSampleCoveragex(GLclampx value, GLboolean invert)
{
	RedFinger_glSampleCoveragex( value, invert);
}

void glScalex(GLfixed x, GLfixed y, GLfixed z)
{
	RedFinger_glScalex( x, y, z);
}

void glScissor(GLint x, GLint y, GLsizei width, GLsizei height)
{
	RedFinger_glScissor( x, y, width, height);
}

void glShadeModel(GLenum mode)
{
	RedFinger_glShadeModel( mode);
}

void glStencilFunc(GLenum func, GLint ref, GLuint mask)
{
	RedFinger_glStencilFunc( func, ref, mask);
}

void glStencilMask(GLuint mask)
{
	RedFinger_glStencilMask( mask);
}

void glStencilOp(GLenum fail, GLenum zfail, GLenum zpass)
{
	RedFinger_glStencilOp( fail, zfail, zpass);
}

void glTexCoordPointer(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer)
{
	RedFinger_glTexCoordPointer( size, type, stride, pointer);
}

void glTexEnvi(GLenum target, GLenum pname, GLint param)
{
	RedFinger_glTexEnvi( target, pname, param);
}

void glTexEnvx(GLenum target, GLenum pname, GLfixed param)
{
	RedFinger_glTexEnvx( target, pname, param);
}

void glTexEnviv(GLenum target, GLenum pname, const GLint* params)
{
	RedFinger_glTexEnviv( target, pname, params);
}

void glTexEnvxv(GLenum target, GLenum pname, const GLfixed* params)
{
	RedFinger_glTexEnvxv( target, pname, params);
}

void glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid* pixels)
{
	RedFinger_glTexImage2D( target, level, internalformat, width, height, border, format, type, pixels);
}

void glTexParameteri(GLenum target, GLenum pname, GLint param)
{
	RedFinger_glTexParameteri( target, pname, param);
}

void glTexParameterx(GLenum target, GLenum pname, GLfixed param)
{
	RedFinger_glTexParameterx( target, pname, param);
}

void glTexParameteriv(GLenum target, GLenum pname, const GLint* params)
{
	RedFinger_glTexParameteriv( target, pname, params);
}

void glTexParameterxv(GLenum target, GLenum pname, const GLfixed* params)
{
	RedFinger_glTexParameterxv( target, pname, params);
}

void glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid* pixels)
{
	RedFinger_glTexSubImage2D( target, level, xoffset, yoffset, width, height, format, type, pixels);
}

void glTranslatex(GLfixed x, GLfixed y, GLfixed z)
{
	RedFinger_glTranslatex( x, y, z);
}

void glVertexPointer(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer)
{
	RedFinger_glVertexPointer( size, type, stride, pointer);
}

void glViewport(GLint x, GLint y, GLsizei width, GLsizei height)
{
	RedFinger_glViewport( x, y, width, height);
}

void glPointSizePointerOES(GLenum type, GLsizei stride, const GLvoid* pointer)
{
	RedFinger_glPointSizePointerOES( type, stride, pointer);
}

void glVertexPointerOffset(GLint size, GLenum type, GLsizei stride, GLuint offset)
{
	RedFinger_glVertexPointerOffset( size, type, stride, offset);
}

void glColorPointerOffset(GLint size, GLenum type, GLsizei stride, GLuint offset)
{
	RedFinger_glColorPointerOffset( size, type, stride, offset);
}

void glNormalPointerOffset(GLenum type, GLsizei stride, GLuint offset)
{
	RedFinger_glNormalPointerOffset( type, stride, offset);
}

void glPointSizePointerOffset(GLenum type, GLsizei stride, GLuint offset)
{
	RedFinger_glPointSizePointerOffset( type, stride, offset);
}

void glTexCoordPointerOffset(GLint size, GLenum type, GLsizei stride, GLuint offset)
{
	RedFinger_glTexCoordPointerOffset( size, type, stride, offset);
}

void glWeightPointerOffset(GLint size, GLenum type, GLsizei stride, GLuint offset)
{
	RedFinger_glWeightPointerOffset( size, type, stride, offset);
}

void glMatrixIndexPointerOffset(GLint size, GLenum type, GLsizei stride, GLuint offset)
{
	RedFinger_glMatrixIndexPointerOffset( size, type, stride, offset);
}

void glVertexPointerData(GLint size, GLenum type, GLsizei stride, void* data, GLuint datalen)
{
	RedFinger_glVertexPointerData( size, type, stride, data, datalen);
}

void glColorPointerData(GLint size, GLenum type, GLsizei stride, void* data, GLuint datalen)
{
	RedFinger_glColorPointerData( size, type, stride, data, datalen);
}

void glNormalPointerData(GLenum type, GLsizei stride, void* data, GLuint datalen)
{
	RedFinger_glNormalPointerData( type, stride, data, datalen);
}

void glTexCoordPointerData(GLint unit, GLint size, GLenum type, GLsizei stride, void* data, GLuint datalen)
{
	RedFinger_glTexCoordPointerData( unit, size, type, stride, data, datalen);
}

void glPointSizePointerData(GLenum type, GLsizei stride, void* data, GLuint datalen)
{
	RedFinger_glPointSizePointerData( type, stride, data, datalen);
}

void glWeightPointerData(GLint size, GLenum type, GLsizei stride, void* data, GLuint datalen)
{
	RedFinger_glWeightPointerData( size, type, stride, data, datalen);
}

void glMatrixIndexPointerData(GLint size, GLenum type, GLsizei stride, void* data, GLuint datalen)
{
	RedFinger_glMatrixIndexPointerData( size, type, stride, data, datalen);
}

void glDrawElementsOffset(GLenum mode, GLsizei count, GLenum type, GLuint offset)
{
	RedFinger_glDrawElementsOffset( mode, count, type, offset);
}

void glDrawElementsData(GLenum mode, GLsizei count, GLenum type, void* data, GLuint datalen)
{
	RedFinger_glDrawElementsData( mode, count, type, data, datalen);
}

void glGetCompressedTextureFormats(int count, GLint* formats)
{
	RedFinger_glGetCompressedTextureFormats( count, formats);
}

int glFinishRoundTrip()
{
	return RedFinger_glFinishRoundTrip();
}

void glBlendEquationSeparateOES(GLenum modeRGB, GLenum modeAlpha)
{
	RedFinger_glBlendEquationSeparateOES( modeRGB, modeAlpha);
}

void glBlendFuncSeparateOES(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
{
	RedFinger_glBlendFuncSeparateOES( srcRGB, dstRGB, srcAlpha, dstAlpha);
}

void glBlendEquationOES(GLenum mode)
{
	RedFinger_glBlendEquationOES( mode);
}

void glDrawTexsOES(GLshort x, GLshort y, GLshort z, GLshort width, GLshort height)
{
	RedFinger_glDrawTexsOES( x, y, z, width, height);
}

void glDrawTexiOES(GLint x, GLint y, GLint z, GLint width, GLint height)
{
	RedFinger_glDrawTexiOES( x, y, z, width, height);
}

void glDrawTexxOES(GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height)
{
	RedFinger_glDrawTexxOES( x, y, z, width, height);
}

void glDrawTexsvOES(const GLshort* coords)
{
	RedFinger_glDrawTexsvOES( coords);
}

void glDrawTexivOES(const GLint* coords)
{
	RedFinger_glDrawTexivOES( coords);
}

void glDrawTexxvOES(const GLfixed* coords)
{
	RedFinger_glDrawTexxvOES( coords);
}

void glDrawTexfOES(GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
{
	RedFinger_glDrawTexfOES( x, y, z, width, height);
}

void glDrawTexfvOES(const GLfloat* coords)
{
	RedFinger_glDrawTexfvOES( coords);
}

void glEGLImageTargetTexture2DOES(GLenum target, GLeglImageOES image)
{
	RedFinger_glEGLImageTargetTexture2DOES( target, image);
}

void glEGLImageTargetRenderbufferStorageOES(GLenum target, GLeglImageOES image)
{
	RedFinger_glEGLImageTargetRenderbufferStorageOES( target, image);
}

void glAlphaFuncxOES(GLenum func, GLclampx ref)
{
	RedFinger_glAlphaFuncxOES( func, ref);
}

void glClearColorxOES(GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
{
	RedFinger_glClearColorxOES( red, green, blue, alpha);
}

void glClearDepthxOES(GLclampx depth)
{
	RedFinger_glClearDepthxOES( depth);
}

void glClipPlanexOES(GLenum plane, const GLfixed* equation)
{
	RedFinger_glClipPlanexOES( plane, equation);
}

void glClipPlanexIMG(GLenum plane, const GLfixed* equation)
{
	RedFinger_glClipPlanexIMG( plane, equation);
}

void glColor4xOES(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
{
	RedFinger_glColor4xOES( red, green, blue, alpha);
}

void glDepthRangexOES(GLclampx zNear, GLclampx zFar)
{
	RedFinger_glDepthRangexOES( zNear, zFar);
}

void glFogxOES(GLenum pname, GLfixed param)
{
	RedFinger_glFogxOES( pname, param);
}

void glFogxvOES(GLenum pname, const GLfixed* params)
{
	RedFinger_glFogxvOES( pname, params);
}

void glFrustumxOES(GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
{
	RedFinger_glFrustumxOES( left, right, bottom, top, zNear, zFar);
}

void glGetClipPlanexOES(GLenum pname, GLfixed* eqn)
{
	RedFinger_glGetClipPlanexOES( pname, eqn);
}

void glGetClipPlanex(GLenum pname, GLfixed* eqn)
{
	RedFinger_glGetClipPlanex( pname, eqn);
}

void glGetFixedvOES(GLenum pname, GLfixed* params)
{
	RedFinger_glGetFixedvOES( pname, params);
}

void glGetLightxvOES(GLenum light, GLenum pname, GLfixed* params)
{
	RedFinger_glGetLightxvOES( light, pname, params);
}

void glGetMaterialxvOES(GLenum face, GLenum pname, GLfixed* params)
{
	RedFinger_glGetMaterialxvOES( face, pname, params);
}

void glGetTexEnvxvOES(GLenum env, GLenum pname, GLfixed* params)
{
	RedFinger_glGetTexEnvxvOES( env, pname, params);
}

void glGetTexParameterxvOES(GLenum target, GLenum pname, GLfixed* params)
{
	RedFinger_glGetTexParameterxvOES( target, pname, params);
}

void glLightModelxOES(GLenum pname, GLfixed param)
{
	RedFinger_glLightModelxOES( pname, param);
}

void glLightModelxvOES(GLenum pname, const GLfixed* params)
{
	RedFinger_glLightModelxvOES( pname, params);
}

void glLightxOES(GLenum light, GLenum pname, GLfixed param)
{
	RedFinger_glLightxOES( light, pname, param);
}

void glLightxvOES(GLenum light, GLenum pname, const GLfixed* params)
{
	RedFinger_glLightxvOES( light, pname, params);
}

void glLineWidthxOES(GLfixed width)
{
	RedFinger_glLineWidthxOES( width);
}

void glLoadMatrixxOES(const GLfixed* m)
{
	RedFinger_glLoadMatrixxOES( m);
}

void glMaterialxOES(GLenum face, GLenum pname, GLfixed param)
{
	RedFinger_glMaterialxOES( face, pname, param);
}

void glMaterialxvOES(GLenum face, GLenum pname, const GLfixed* params)
{
	RedFinger_glMaterialxvOES( face, pname, params);
}

void glMultMatrixxOES(const GLfixed* m)
{
	RedFinger_glMultMatrixxOES( m);
}

void glMultiTexCoord4xOES(GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
{
	RedFinger_glMultiTexCoord4xOES( target, s, t, r, q);
}

void glNormal3xOES(GLfixed nx, GLfixed ny, GLfixed nz)
{
	RedFinger_glNormal3xOES( nx, ny, nz);
}

void glOrthoxOES(GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
{
	RedFinger_glOrthoxOES( left, right, bottom, top, zNear, zFar);
}

void glPointParameterxOES(GLenum pname, GLfixed param)
{
	RedFinger_glPointParameterxOES( pname, param);
}

void glPointParameterxvOES(GLenum pname, const GLfixed* params)
{
	RedFinger_glPointParameterxvOES( pname, params);
}

void glPointSizexOES(GLfixed size)
{
	RedFinger_glPointSizexOES( size);
}

void glPolygonOffsetxOES(GLfixed factor, GLfixed units)
{
	RedFinger_glPolygonOffsetxOES( factor, units);
}

void glRotatexOES(GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
{
	RedFinger_glRotatexOES( angle, x, y, z);
}

void glSampleCoveragexOES(GLclampx value, GLboolean invert)
{
	RedFinger_glSampleCoveragexOES( value, invert);
}

void glScalexOES(GLfixed x, GLfixed y, GLfixed z)
{
	RedFinger_glScalexOES( x, y, z);
}

void glTexEnvxOES(GLenum target, GLenum pname, GLfixed param)
{
	RedFinger_glTexEnvxOES( target, pname, param);
}

void glTexEnvxvOES(GLenum target, GLenum pname, const GLfixed* params)
{
	RedFinger_glTexEnvxvOES( target, pname, params);
}

void glTexParameterxOES(GLenum target, GLenum pname, GLfixed param)
{
	RedFinger_glTexParameterxOES( target, pname, param);
}

void glTexParameterxvOES(GLenum target, GLenum pname, const GLfixed* params)
{
	RedFinger_glTexParameterxvOES( target, pname, params);
}

void glTranslatexOES(GLfixed x, GLfixed y, GLfixed z)
{
	RedFinger_glTranslatexOES( x, y, z);
}

GLboolean glIsRenderbufferOES(GLuint renderbuffer)
{
	return RedFinger_glIsRenderbufferOES( renderbuffer);
}

void glBindRenderbufferOES(GLenum target, GLuint renderbuffer)
{
	RedFinger_glBindRenderbufferOES( target, renderbuffer);
}

void glDeleteRenderbuffersOES(GLsizei n, const GLuint* renderbuffers)
{
	RedFinger_glDeleteRenderbuffersOES( n, renderbuffers);
}

void glGenRenderbuffersOES(GLsizei n, GLuint* renderbuffers)
{
	RedFinger_glGenRenderbuffersOES( n, renderbuffers);
}

void glRenderbufferStorageOES(GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
{
	RedFinger_glRenderbufferStorageOES( target, internalformat, width, height);
}

void glGetRenderbufferParameterivOES(GLenum target, GLenum pname, GLint* params)
{
	RedFinger_glGetRenderbufferParameterivOES( target, pname, params);
}

GLboolean glIsFramebufferOES(GLuint framebuffer)
{
	return RedFinger_glIsFramebufferOES( framebuffer);
}

void glBindFramebufferOES(GLenum target, GLuint framebuffer)
{
	RedFinger_glBindFramebufferOES( target, framebuffer);
}

void glDeleteFramebuffersOES(GLsizei n, const GLuint* framebuffers)
{
	RedFinger_glDeleteFramebuffersOES( n, framebuffers);
}

void glGenFramebuffersOES(GLsizei n, GLuint* framebuffers)
{
	RedFinger_glGenFramebuffersOES( n, framebuffers);
}

GLenum glCheckFramebufferStatusOES(GLenum target)
{
	return RedFinger_glCheckFramebufferStatusOES( target);
}

void glFramebufferRenderbufferOES(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
{
	RedFinger_glFramebufferRenderbufferOES( target, attachment, renderbuffertarget, renderbuffer);
}

void glFramebufferTexture2DOES(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
{
	RedFinger_glFramebufferTexture2DOES( target, attachment, textarget, texture, level);
}

void glGetFramebufferAttachmentParameterivOES(GLenum target, GLenum attachment, GLenum pname, GLint* params)
{
	RedFinger_glGetFramebufferAttachmentParameterivOES( target, attachment, pname, params);
}

void glGenerateMipmapOES(GLenum target)
{
	RedFinger_glGenerateMipmapOES( target);
}

void* glMapBufferOES(GLenum target, GLenum access)
{
	ALOGD("run function:%s,%d\n",__func__,__LINE__);
	GET_CONTEXT_wrapper; 
	 return ctx->glMapBufferOES( target, access);
}

GLboolean glUnmapBufferOES(GLenum target)
{
	return RedFinger_glUnmapBufferOES( target);
}

void glGetBufferPointervOES(GLenum target, GLenum pname, GLvoid** params)
{
	ALOGD("run function:%s,%d\n",__func__,__LINE__);
	GET_CONTEXT_wrapper; 
	 ctx->glGetBufferPointervOES( target, pname, params);
}

void glCurrentPaletteMatrixOES(GLuint matrixpaletteindex)
{
	RedFinger_glCurrentPaletteMatrixOES( matrixpaletteindex);
}

void glLoadPaletteFromModelViewMatrixOES()
{
	RedFinger_glLoadPaletteFromModelViewMatrixOES();
}

void glMatrixIndexPointerOES(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer)
{
	RedFinger_glMatrixIndexPointerOES( size, type, stride, pointer);
}

void glWeightPointerOES(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer)
{
	RedFinger_glWeightPointerOES( size, type, stride, pointer);
}

GLbitfield glQueryMatrixxOES(GLfixed* mantissa, GLint* exponent)
{
	return RedFinger_glQueryMatrixxOES( mantissa, exponent);
}

void glDepthRangefOES(GLclampf zNear, GLclampf zFar)
{
	RedFinger_glDepthRangefOES( zNear, zFar);
}

void glFrustumfOES(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
{
	RedFinger_glFrustumfOES( left, right, bottom, top, zNear, zFar);
}

void glOrthofOES(GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
{
	RedFinger_glOrthofOES( left, right, bottom, top, zNear, zFar);
}

void glClipPlanefOES(GLenum plane, const GLfloat* equation)
{
	RedFinger_glClipPlanefOES( plane, equation);
}

void glClipPlanefIMG(GLenum plane, const GLfloat* equation)
{
	RedFinger_glClipPlanefIMG( plane, equation);
}

void glGetClipPlanefOES(GLenum pname, GLfloat* eqn)
{
	RedFinger_glGetClipPlanefOES( pname, eqn);
}

void glClearDepthfOES(GLclampf depth)
{
	RedFinger_glClearDepthfOES( depth);
}

void glTexGenfOES(GLenum coord, GLenum pname, GLfloat param)
{
	RedFinger_glTexGenfOES( coord, pname, param);
}

void glTexGenfvOES(GLenum coord, GLenum pname, const GLfloat* params)
{
	RedFinger_glTexGenfvOES( coord, pname, params);
}

void glTexGeniOES(GLenum coord, GLenum pname, GLint param)
{
	RedFinger_glTexGeniOES( coord, pname, param);
}

void glTexGenivOES(GLenum coord, GLenum pname, const GLint* params)
{
	RedFinger_glTexGenivOES( coord, pname, params);
}

void glTexGenxOES(GLenum coord, GLenum pname, GLfixed param)
{
	RedFinger_glTexGenxOES( coord, pname, param);
}

void glTexGenxvOES(GLenum coord, GLenum pname, const GLfixed* params)
{
	RedFinger_glTexGenxvOES( coord, pname, params);
}

void glGetTexGenfvOES(GLenum coord, GLenum pname, GLfloat* params)
{
	RedFinger_glGetTexGenfvOES( coord, pname, params);
}

void glGetTexGenivOES(GLenum coord, GLenum pname, GLint* params)
{
	RedFinger_glGetTexGenivOES( coord, pname, params);
}

void glGetTexGenxvOES(GLenum coord, GLenum pname, GLfixed* params)
{
	RedFinger_glGetTexGenxvOES( coord, pname, params);
}

void glBindVertexArrayOES(GLuint array)
{
	RedFinger_glBindVertexArrayOES( array);
}

void glDeleteVertexArraysOES(GLsizei n, const GLuint* arrays)
{
	RedFinger_glDeleteVertexArraysOES( n, arrays);
}

void glGenVertexArraysOES(GLsizei n, GLuint* arrays)
{
	RedFinger_glGenVertexArraysOES( n, arrays);
}

GLboolean glIsVertexArrayOES(GLuint array)
{
	return RedFinger_glIsVertexArrayOES( array);
}

void glDiscardFramebufferEXT(GLenum target, GLsizei numAttachments, const GLenum* attachments)
{
	RedFinger_glDiscardFramebufferEXT( target, numAttachments, attachments);
}

void glMultiDrawArraysEXT(GLenum mode, const GLint* first, const GLsizei* count, GLsizei primcount)
{
	ALOGD("run function:%s,%d\n",__func__,__LINE__);
	GET_CONTEXT_wrapper; 
	 ctx->glMultiDrawArraysEXT( mode, first, count, primcount);
}

void glMultiDrawElementsEXT(GLenum mode, const GLsizei* count, GLenum type, const GLvoid*const* indices, GLsizei primcount)
{
	ALOGD("run function:%s,%d\n",__func__,__LINE__);
	GET_CONTEXT_wrapper; 
	 ctx->glMultiDrawElementsEXT( mode, count, type, indices, primcount);
}

void glMultiDrawArraysSUN(GLenum mode, GLint* first, GLsizei* count, GLsizei primcount)
{
	ALOGD("run function:%s,%d\n",__func__,__LINE__);
	GET_CONTEXT_wrapper; 
	 ctx->glMultiDrawArraysSUN( mode, first, count, primcount);
}

void glMultiDrawElementsSUN(GLenum mode, const GLsizei* count, GLenum type, const GLvoid** indices, GLsizei primcount)
{
	ALOGD("run function:%s,%d\n",__func__,__LINE__);
	GET_CONTEXT_wrapper; 
	 ctx->glMultiDrawElementsSUN( mode, count, type, indices, primcount);
}

void glRenderbufferStorageMultisampleIMG(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
{
	RedFinger_glRenderbufferStorageMultisampleIMG( target, samples, internalformat, width, height);
}

void glFramebufferTexture2DMultisampleIMG(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLsizei samples)
{
	RedFinger_glFramebufferTexture2DMultisampleIMG( target, attachment, textarget, texture, level, samples);
}

void glDeleteFencesNV(GLsizei n, const GLuint* fences)
{
	RedFinger_glDeleteFencesNV( n, fences);
}

void glGenFencesNV(GLsizei n, GLuint* fences)
{
	RedFinger_glGenFencesNV( n, fences);
}

GLboolean glIsFenceNV(GLuint fence)
{
	return RedFinger_glIsFenceNV( fence);
}

GLboolean glTestFenceNV(GLuint fence)
{
	return RedFinger_glTestFenceNV( fence);
}

void glGetFenceivNV(GLuint fence, GLenum pname, GLint* params)
{
	RedFinger_glGetFenceivNV( fence, pname, params);
}

void glFinishFenceNV(GLuint fence)
{
	RedFinger_glFinishFenceNV( fence);
}

void glSetFenceNV(GLuint fence, GLenum condition)
{
	RedFinger_glSetFenceNV( fence, condition);
}

void glGetDriverControlsQCOM(GLint* num, GLsizei size, GLuint* driverControls)
{
	RedFinger_glGetDriverControlsQCOM( num, size, driverControls);
}

void glGetDriverControlStringQCOM(GLuint driverControl, GLsizei bufSize, GLsizei* length, GLchar* driverControlString)
{
	RedFinger_glGetDriverControlStringQCOM( driverControl, bufSize, length, driverControlString);
}

void glEnableDriverControlQCOM(GLuint driverControl)
{
	RedFinger_glEnableDriverControlQCOM( driverControl);
}

void glDisableDriverControlQCOM(GLuint driverControl)
{
	RedFinger_glDisableDriverControlQCOM( driverControl);
}

void glExtGetTexturesQCOM(GLuint* textures, GLint maxTextures, GLint* numTextures)
{
	RedFinger_glExtGetTexturesQCOM( textures, maxTextures, numTextures);
}

void glExtGetBuffersQCOM(GLuint* buffers, GLint maxBuffers, GLint* numBuffers)
{
	RedFinger_glExtGetBuffersQCOM( buffers, maxBuffers, numBuffers);
}

void glExtGetRenderbuffersQCOM(GLuint* renderbuffers, GLint maxRenderbuffers, GLint* numRenderbuffers)
{
	RedFinger_glExtGetRenderbuffersQCOM( renderbuffers, maxRenderbuffers, numRenderbuffers);
}

void glExtGetFramebuffersQCOM(GLuint* framebuffers, GLint maxFramebuffers, GLint* numFramebuffers)
{
	RedFinger_glExtGetFramebuffersQCOM( framebuffers, maxFramebuffers, numFramebuffers);
}

void glExtGetTexLevelParameterivQCOM(GLuint texture, GLenum face, GLint level, GLenum pname, GLint* params)
{
	RedFinger_glExtGetTexLevelParameterivQCOM( texture, face, level, pname, params);
}

void glExtTexObjectStateOverrideiQCOM(GLenum target, GLenum pname, GLint param)
{
	RedFinger_glExtTexObjectStateOverrideiQCOM( target, pname, param);
}

void glExtGetTexSubImageQCOM(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLvoid* texels)
{
	RedFinger_glExtGetTexSubImageQCOM( target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, texels);
}

void glExtGetBufferPointervQCOM(GLenum target, GLvoid** params)
{
	ALOGD("run function:%s,%d\n",__func__,__LINE__);
	GET_CONTEXT_wrapper; 
	 ctx->glExtGetBufferPointervQCOM( target, params);
}

void glExtGetShadersQCOM(GLuint* shaders, GLint maxShaders, GLint* numShaders)
{
	RedFinger_glExtGetShadersQCOM( shaders, maxShaders, numShaders);
}

void glExtGetProgramsQCOM(GLuint* programs, GLint maxPrograms, GLint* numPrograms)
{
	RedFinger_glExtGetProgramsQCOM( programs, maxPrograms, numPrograms);
}

GLboolean glExtIsProgramBinaryQCOM(GLuint program)
{
	return RedFinger_glExtIsProgramBinaryQCOM( program);
}

void glExtGetProgramBinarySourceQCOM(GLuint program, GLenum shadertype, GLchar* source, GLint* length)
{
	ALOGD("run function:%s,%d\n",__func__,__LINE__);
	GET_CONTEXT_wrapper; 
	 ctx->glExtGetProgramBinarySourceQCOM( program, shadertype, source, length);
}

void glStartTilingQCOM(GLuint x, GLuint y, GLuint width, GLuint height, GLbitfield preserveMask)
{
	RedFinger_glStartTilingQCOM( x, y, width, height, preserveMask);
}

void glEndTilingQCOM(GLbitfield preserveMask)
{
	RedFinger_glEndTilingQCOM( preserveMask);
}

