// Generated Code - DO NOT EDIT !!
// generated by 'emugen'

#ifndef GUARD_gl2_decoder_context_t
#define GUARD_gl2_decoder_context_t

#include "IOStream.h" 
#include "gl2_server_context.h"



struct gl2_decoder_context_t : public gl2_server_context_t {

	size_t decode(void *buf, size_t bufsize, IOStream *stream);

};

#endif
