// Generated Code - DO NOT EDIT !!
// generated by 'emugen'

#ifndef GUARD_gles_decoder_context_t
#define GUARD_gles_decoder_context_t

#include "IOStream.h" 
#include "gles_server_context.h"



struct gles_decoder_context_t : public gles_server_context_t {

	size_t decode(void *buf, size_t bufsize, IOStream *stream);

};

#endif
